{% set name = "imaginairy" %}
{% set version = "14.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brycedrennan/imaginAIry/archive/{{ version }}.tar.gz
  sha256: f5f0610eddb89ee5e8a29d9fab09c9bb95202558c9f4fdea8f76fa2f9732a3f4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - imagine = imaginairy.cli.main:imagine_cmd
    - aimg = imaginairy.cli.main:aimg

requirements:
  host:
    - python >=3.6,<3.12
    - pip
  run:
    - python >=3.6,<3.12
    - click >=8.0.0
    - click-shell
    - click-help-colors
    - protobuf !=3.20.2, !=3.19.5
    - facexlib
    - fairscale >=0.4.4  # for vendored blip
    - ftfy  # for vendored clip
    - pytorch >=2.1.0
    - numpy <1.26.0, >=1.19.0
    - tqdm
    - diffusers
    - imageio >=2.9.0
    - jaxtyping
    - pillow >=8.0.0
    - psutil
    - pytorch-lightning <2.0.0,>=1.4.2
    - omegaconf >=2.1.1
    - open-clip-torch
    - py-opencv
    - requests
    - einops >=0.3.0
    - safetensors >=0.4.0
    - timm >=0.4.12  # for vendored blip
    - torchdiffeq
    - transformers >=4.19.2
    - torchmetrics >=0.6.0
    - torchvision >=0.13.1
    - triton
    - kornia >=0.6
    - xformers
    - fastapi
    - pydantic
    - uvicorn
    - scipy <1.11
    - huggingface-hub >=0.19.4

test:
  imports:
    - imaginairy
  requires:
    - pip
  commands:
    - pip check
    - imagine --help
    - aimg --help

about:
  home: https://github.com/brycedrennan/imaginAIry
  summary: AI imagined images. Pythonic generation of stable diffusion images.
  description: |
    AI imagined images. Pythonic generation of stable diffusion images.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/brycedrennan/imaginAIry
  dev_url: https://github.com/brycedrennan/imaginAIry

extra:
  recipe-maintainers:
    - brycedrennan
    - jan-janssen
